export enum Action {
  READ = 'READ',
  CREATE = 'CREATE',
  UPDATE = 'UPDATE',
  DELETE = 'DELETE',
  EDIT_PRICES = 'EDIT_PRICES',
}

export enum Resource {
  EMPLOYEES = 'EMPLOYEES',
  PRODUCTS = 'PRODUCTS',
  SUPPLIES = 'SUPPLIES',
  OUTFLOWS = 'OUTFLOWS',
  SALES = 'SALES',
  PLATFORMS = 'PLATFORMS',
}
